version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/bankDB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



# docker-compose up --build